#pragma once

#include <builtinFonts/notoserif_12_bold.h>
#include <builtinFonts/notoserif_12_bolditalic.h>
#include <builtinFonts/notoserif_12_italic.h>
#include <builtinFonts/notoserif_12_regular.h>
#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
// UI chrome fonts: one tier per device class. main.cpp registers whichever
// tier is compiled here under the same font slots (small / UI_10 / UI_12).
#if FREEINK_DEVICE_EMINIMAL
// The 1.5x UI tier for the 7.8" panel (uiScale 1.5 in its profile): the same
// Ubuntu/Hebrew/Arabic/Vietnamese stack and intervals as the 10/12 fonts,
// generated by convert-builtin-fonts.sh's UI recipe at 15/18, plus a 12 px
// NotoSans small font. Only this device links them (~400 KB of flash). The
// 8/10/12 tier below is not compiled for it: the linker already dropped it as
// unreferenced (firmware.map, 2026-09-20), this just spares main.cpp parsing
// 1.4 MB of headers for nothing.
#include <builtinFonts/notosans_12_small.h>
#include <builtinFonts/ubuntu_15_bold.h>
#include <builtinFonts/ubuntu_15_regular.h>
#include <builtinFonts/ubuntu_18_bold.h>
#include <builtinFonts/ubuntu_18_regular.h>
#else
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
#endif
